services:
  redis:
    image: redis:7-alpine
    container_name: edunary-redis
    restart: always
    command: redis-server --requirepass Hello@123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "Hello@123", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data: