// Mock data for Student Q&A tab
// Data shape matches future API: CourseQuestion + CourseAnswer + QuestionUpvote/AnswerUpvote

export const STUDENT_MOCK_QUESTIONS = [
  {
    id: 1,
    courseId: 1,
    itemId: "item-3",           // matches currentItem.itemId from course JSON
    lectureName: "Redux Thunk Middleware",
    title: "Why does my dispatch not trigger the API call?",
    detail: "<p>I'm using <strong>redux-thunk</strong> and created an async action creator, but when I dispatch it nothing happens. The API call never fires. Here's my setup:</p><pre>const fetchData = () => async (dispatch) => { ... }</pre>",
    authorName: "Nguyễn Văn An",
    authorAvatar: "https://i.pravatar.cc/40?img=1",
    answerCount: 3,
    upvoteCount: 12,
    isFeatured: true,
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
  },
  {
    id: 2,
    courseId: 1,
    itemId: "item-5",
    lectureName: "React Context vs Redux",
    title: "When should I use Context API instead of Redux?",
    detail: "<p>I've been trying to understand the tradeoffs. In what scenarios is Context API better?</p>",
    authorName: "Trần Thị Mai",
    authorAvatar: "https://i.pravatar.cc/40?img=5",
    answerCount: 0,
    upvoteCount: 5,
    isFeatured: false,
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 19 * 60).toISOString(),
  },
  {
    id: 3,
    courseId: 1,
    itemId: "item-3",
    lectureName: "Redux Thunk Middleware",
    title: "First Question Answer",
    detail: "<p>First Question Answer</p>",
    authorName: "Trần Huy Hoàng",
    authorAvatar: "https://i.pravatar.cc/40?img=7",
    answerCount: 1,
    upvoteCount: 0,
    isFeatured: false,
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
  },
  {
    id: 4,
    courseId: 1,
    itemId: "item-3",
    lectureName: "Redux Thunk Middleware",
    title: "Question about how can i click study",
    detail: null,
    authorName: "Phạm Hương Ly",
    authorAvatar: "https://i.pravatar.cc/40?img=11",
    answerCount: 0,
    upvoteCount: 0,
    isFeatured: false,
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 17).toISOString(),
  },
  {
    id: 5,
    courseId: 1,
    itemId: "item-2",
    lectureName: "useEffect Deep Dive",
    title: "useEffect firing twice in React 18 strict mode?",
    detail: "<p>I noticed my useEffect runs twice on mount in development. Is this expected?</p>",
    authorName: "Vũ Minh Tuấn",
    authorAvatar: "https://i.pravatar.cc/40?img=15",
    answerCount: 2,
    upvoteCount: 18,
    isFeatured: false,
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
];

export const STUDENT_MOCK_ANSWERS = {
  1: [
    {
      id: 101,
      questionId: 1,
      body: "<p>hello, how are you?</p><img src='https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Camponotus_flavomarginatus_ant.jpg/320px-Camponotus_flavomarginatus_ant.jpg' style='max-width:100%; border-radius:8px; margin-top:8px;' alt='example'/>",
      isTopAnswer: false,
      upvoteCount: 1,
      authorName: "An Nguyen",
      authorAvatar: "https://i.pravatar.cc/40?img=33",
      isInstructor: true,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
    },
    {
      id: 102,
      questionId: 1,
      body: "<p>but how can i ...</p>",
      isTopAnswer: true,
      upvoteCount: 0,
      authorName: "Huy Hoàng",
      authorAvatar: "https://i.pravatar.cc/40?img=7",
      isInstructor: true,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 19).toISOString(),
    },
    {
      id: 103,
      questionId: 1,
      body: "<p>Also check that your action creator returns a function, not a plain object. Thunk intercepts functions and passes <code>dispatch</code> and <code>getState</code> to them.</p>",
      isTopAnswer: false,
      upvoteCount: 1,
      authorName: "Huy Hoàng",
      authorAvatar: "https://i.pravatar.cc/40?img=7",
      isInstructor: true,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    },
  ],
  3: [
    {
      id: 301,
      questionId: 3,
      body: "<p>Great question! You should consider Context when the state is relatively simple and doesn't change too frequently. Redux is better for complex state logic and frequent updates.</p>",
      isTopAnswer: true,
      upvoteCount: 4,
      authorName: "An Nguyen",
      authorAvatar: "https://i.pravatar.cc/40?img=33",
      isInstructor: true,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 16).toISOString(),
    },
  ],
  5: [
    {
      id: 501,
      questionId: 5,
      body: "<p>Yes, this is expected in React 18 Strict Mode during development only. React mounts, unmounts, and remounts to detect side effects. Always return a cleanup function.</p>",
      isTopAnswer: true,
      upvoteCount: 12,
      authorName: "An Nguyen",
      authorAvatar: "https://i.pravatar.cc/40?img=33",
      isInstructor: true,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 40).toISOString(),
    },
    {
      id: 502,
      questionId: 5,
      body: "<p>Use an AbortController to cancel API calls on cleanup — this avoids state updates on unmounted components.</p>",
      isTopAnswer: false,
      upvoteCount: 4,
      authorName: "Trần Văn Khoa",
      authorAvatar: "https://i.pravatar.cc/40?img=30",
      isInstructor: false,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 38).toISOString(),
    },
  ],
};

export const CURRENT_USER = {
  id: "mock-user-id",
  name: "You",
  avatar: "https://i.pravatar.cc/40?img=12",
};
