import { useQuery } from "@tanstack/react-query";
import { ServiceHealthClient } from "../../web-api-client.ts";

// ServiceHealthClient is generated by NSwag after a Debug build.
// Run: dotnet build src.sln (Debug) to regenerate web-api-client.ts.
const useGetServiceHealth = () =>
    useQuery({
        queryKey: ["service-health"],
        queryFn: async () => {
            const client = new ServiceHealthClient();
            return await client.getServiceHealth();
        },
        refetchInterval: 30 * 1000, // auto-refresh every 30s
        staleTime: 10 * 1000,
    });

export default useGetServiceHealth;
