import { useQuery } from "@tanstack/react-query";
import { ServiceHealthClient } from "../../web-api-client.ts";

// ServiceHealthClient is generated by NSwag after a Debug build.
// Run: dotnet build src.sln (Debug) to regenerate web-api-client.ts.
const useGetServiceHealth = () =>
    useQuery({
        queryKey: ["service-health"],
        queryFn: async () => {
            const client = new ServiceHealthClient();
            return await client.getServiceHealth();
        },
        // Match the server-side cache window (GetServiceHealthQuery.CacheDuration = 60s);
        refetchInterval: 60 * 1000,
        staleTime: 60 * 1000,
    });

export default useGetServiceHealth;
