// Mock data for Q&A Dashboard — replace with real API hooks later

export const MOCK_COURSES = [
  { id: null, title: "All courses" },
  { id: 1, title: "Complete React & Redux Developer" },
  { id: 2, title: "ASP.NET Core Clean Architecture" },
  { id: 3, title: "Advanced TypeScript Masterclass" },
];

export const MOCK_QUESTIONS = [
  {
    id: 1,
    courseId: 1,
    courseTitle: "Complete React & Redux Developer",
    itemId: "item-3",
    lectureName: "Redux Thunk Middleware",
    title: "Why does my dispatch not trigger the API call?",
    detail: "<p>I'm using <code>redux-thunk</code> and created an async action creator, but when I dispatch it nothing happens. The API call never fires. Here's my code...</p>",
    authorName: "Nguyễn Văn An",
    authorAvatar: "https://i.pravatar.cc/40?img=1",
    answerCount: 3,
    upvoteCount: 12,
    isFeatured: true,
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: 2,
    courseId: 1,
    courseTitle: "Complete React & Redux Developer",
    itemId: "item-5",
    lectureName: "React Context vs Redux",
    title: "When should I use Context API instead of Redux?",
    detail: "<p>I've been trying to understand the tradeoffs. In what scenarios is Context API better than Redux?</p>",
    authorName: "Trần Thị Mai",
    authorAvatar: "https://i.pravatar.cc/40?img=5",
    answerCount: 0,
    upvoteCount: 5,
    isFeatured: false,
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
  },
  {
    id: 3,
    courseId: 2,
    courseTitle: "ASP.NET Core Clean Architecture",
    itemId: null,
    lectureName: null,
    title: "How to properly inject services in Application layer?",
    detail: null,
    authorName: "Lê Quốc Bảo",
    authorAvatar: "https://i.pravatar.cc/40?img=8",
    answerCount: 1,
    upvoteCount: 7,
    isFeatured: false,
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: 4,
    courseId: 1,
    courseTitle: "Complete React & Redux Developer",
    itemId: "item-2",
    lectureName: "useEffect Deep Dive",
    title: "useEffect firing twice in React 18 strict mode?",
    detail: "<p>I noticed my useEffect runs twice on mount in development. Is this expected behavior and how do I handle cleanup properly?</p>",
    authorName: "Phạm Hương Ly",
    authorAvatar: "https://i.pravatar.cc/40?img=11",
    answerCount: 2,
    upvoteCount: 18,
    isFeatured: false,
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: 5,
    courseId: 3,
    courseTitle: "Advanced TypeScript Masterclass",
    itemId: "item-1",
    lectureName: "Generic Constraints",
    title: "Cannot use keyof with generic T in my utility type",
    detail: "<p>I'm building a DeepPartial utility type and hitting a wall with <code>keyof T</code> constraints. TypeScript says the type is not assignable...</p>",
    authorName: "Vũ Minh Tuấn",
    authorAvatar: "https://i.pravatar.cc/40?img=15",
    answerCount: 0,
    upvoteCount: 3,
    isFeatured: false,
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
];

export const MOCK_ANSWERS = {
  1: [
    {
      id: 101,
      questionId: 1,
      body: "<p>The most common cause is forgetting to apply the <code>thunk</code> middleware. Make sure you have <code>applyMiddleware(thunk)</code> in your store configuration. With Redux Toolkit, it's included by default via <code>configureStore()</code>.</p>",
      isTopAnswer: true,
      upvoteCount: 8,
      authorName: "Instructor",
      authorAvatar: "https://i.pravatar.cc/40?img=33",
      isInstructor: true,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    },
    {
      id: 102,
      questionId: 1,
      body: "<p>Also check that your action creator actually returns a function, not an object. Thunk middleware intercepts functions and passes dispatch/getState to them.</p>",
      isTopAnswer: false,
      upvoteCount: 3,
      authorName: "Nguyễn Văn Hùng",
      authorAvatar: "https://i.pravatar.cc/40?img=20",
      isInstructor: false,
      createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    },
    {
      id: 103,
      questionId: 1,
      body: "<p>I had the same issue. In my case I was using the old <code>createStore</code> without applying middleware. Switching to RTK fixed it immediately.</p>",
      isTopAnswer: false,
      upvoteCount: 1,
      authorName: "Đặng Thùy Linh",
      authorAvatar: "https://i.pravatar.cc/40?img=25",
      isInstructor: false,
      createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    },
  ],
  3: [
    {
      id: 301,
      questionId: 3,
      body: "<p>In Clean Architecture, services defined in Application layer should be abstracted as interfaces in <code>Application/Common/Interfaces/</code>. The actual implementation goes in Infrastructure. You inject the interface, not the concrete class. This keeps Application free of infrastructure dependencies.</p>",
      isTopAnswer: true,
      upvoteCount: 5,
      authorName: "Instructor",
      authorAvatar: "https://i.pravatar.cc/40?img=33",
      isInstructor: true,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    },
  ],
  4: [
    {
      id: 401,
      questionId: 4,
      body: "<p>Yes, this is expected in React 18 Strict Mode during development only. React intentionally mounts, unmounts, and remounts components to help detect side effects. In production this does not happen. The fix is to always return a cleanup function from your useEffect.</p>",
      isTopAnswer: true,
      upvoteCount: 12,
      authorName: "Instructor",
      authorAvatar: "https://i.pravatar.cc/40?img=33",
      isInstructor: true,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 40).toISOString(),
    },
    {
      id: 402,
      questionId: 4,
      body: "<p>To add to the instructor's answer — if you're making API calls in useEffect, use an AbortController to cancel the request on cleanup. This avoids state updates on unmounted components.</p>",
      isTopAnswer: false,
      upvoteCount: 4,
      authorName: "Trần Văn Khoa",
      authorAvatar: "https://i.pravatar.cc/40?img=30",
      isInstructor: false,
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 38).toISOString(),
    },
  ],
};
